language: node_js
node_js:
- node
env:
  global:
  - ENCRYPTION_LABEL: "3c0a008cf0db"
  - COMMIT_AUTHOR_EMAIL: "royNiladri@users.noreply.github.com"
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
script: gulp bundle
after_success:
- git config user.email "royNiladri@users.noreply.github.com"
- eval $(ssh-agent -s)
- ssh-add deploy_key
- git add dist/*
- git commit -m "refresh dist folder"
- git push
before_install:
- openssl aes-256-cbc -K $encrypted_3c0a008cf0db_key -iv $encrypted_3c0a008cf0db_iv
  -in deploy_key.enc -out deploy_key -d
