language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g gulp-cli
script: gulp bundle
after_success:
  - git add dist/*
  - git commit -m "refresh dist folder"
  - git push