language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
script: gulp bundle
after_success:
- git add dist/*
- git commit -m "refresh dist folder"
- git push
before_install:
- openssl aes-256-cbc -K $encrypted_3c0a008cf0db_key -iv $encrypted_3c0a008cf0db_iv
  -in deploy_key.enc -out deploy_key -d
