language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_script:
- npm install -g jasmine
script: npm run travis-test
deploy:
  provider: npm
  email: "callniladri.pro@gmail.com"
  api_key: "fa2de746-780d-467a-952e-fad4f2f213a0"
  on:
    branch: master
    tags: true
