language: node_js
node_js:
- node
branches:
  only:
  - master
  - development
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  - npm i -g npm
script: npm run travis-test
after_success: npm run coverage