language: node_js
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "royNiladri@users.noreply.github.com"
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g gulp-cli
script: gulp bundle
after_success:
  - git add dist/*
  - git commit -m "refresh dist folder"
  - git push